[features]
resolution = true
skip-lint = false

[programs.localnet]
discount_platform = "9P3wW4XQH7DntMqfEiLqS6SNztihxfenNUSqECh3WTf3" 

[programs.devnet]
discount_platform = "9P3wW4XQH7DntMqfEiLqS6SNztihxfenNUSqECh3WTf3"

[programs.testnet]
discount_platform = "9P3wW4XQH7DntMqfEiLqS6SNztihxfenNUSqECh3WTf3"

[programs.mainnet]
discount_platform = "9P3wW4XQH7DntMqfEiLqS6SNztihxfenNUSqECh3WTf3"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
#test = "cargo test"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"



[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false
#upgradeable = true

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "deps/mpl_token_metadata.so"